export const interestingFacts = [
  "The human brain weighs about 3 pounds and uses 20% of the body's energy.",
  "Honey never spoils. Archaeologists found 3,000-year-old honey in Egyptian tombs that was still edible.",
  "A day on Venus is longer than its year. It takes 243 Earth days to rotate once but only 225 days to orbit the Sun.",
  "Octopuses have three hearts and blue blood.",
  "Bananas are berries, but strawberries aren't.",
  "The shortest war in history lasted 38 minutes between Britain and Zanzibar in 1896.",
  "Your nose can remember 50,000 different scents.",
  "A group of flamingos is called a 'flamboyance'.",
  "The Eiffel Tower can grow up to 6 inches taller during summer due to thermal expansion.",
  "Sea otters hold hands while sleeping to keep from drifting apart.",
  "There are more stars in the universe than grains of sand on all Earth's beaches.",
  "A bolt of lightning is five times hotter than the surface of the sun.",
  "Butterflies can taste with their feet.",
  "The Great Wall of China is not visible from space without aid.",
  "Dolphins have names for each other.",
  "A sneeze travels out of your mouth at over 100 mph.",
  "The average person will spend six months of their life waiting for red lights to turn green.",
  "Hot water freezes faster than cold water under certain conditions (Mpemba effect).",
  "Elephants are the only mammals that can't jump.",
  "The world's oldest known recipe is for beer and dates back to 3,900 BC.",
]
